"""Drop unused refund_requests fields

Revision ID: 45e411cf3a07
Revises: 20260423_0013
Create Date: 2026-05-08 22:53:59.986463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '45e411cf3a07'
down_revision = '20260423_0013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_refund_requests_claimed_by_admin_user_id_users'), 'refund_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_refund_requests_decided_by_admin_user_id_users'), 'refund_requests', type_='foreignkey')
    op.drop_column('refund_requests', 'claimed_at')
    op.drop_column('refund_requests', 'reviewer_note')
    op.drop_column('refund_requests', 'claimed_by_admin_user_id')
    op.drop_column('refund_requests', 'escalation_status')
    op.drop_column('refund_requests', 'decided_by_admin_user_id')
    op.drop_column('refund_requests', 'escalation_payload_json')
    op.drop_column('refund_requests', 'escalation_sla_deadline_at')
    op.drop_column('refund_requests', 'escalation_queue_name')
    op.drop_column('refund_requests', 'decided_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund_requests', sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('refund_requests', sa.Column('escalation_queue_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('refund_requests', sa.Column('escalation_sla_deadline_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('refund_requests', sa.Column('escalation_payload_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('refund_requests', sa.Column('decided_by_admin_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('refund_requests', sa.Column('escalation_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('refund_requests', sa.Column('claimed_by_admin_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('refund_requests', sa.Column('reviewer_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('refund_requests', sa.Column('claimed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_refund_requests_decided_by_admin_user_id_users'), 'refund_requests', 'users', ['decided_by_admin_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_refund_requests_claimed_by_admin_user_id_users'), 'refund_requests', 'users', ['claimed_by_admin_user_id'], ['id'])
    # ### end Alembic commands ###
